# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52a637d35fdebf46f9fc92792c04c72e92da48a560d9ef8c073c345fd23234b57b3c5cf5b99ed647a3e2433fb28882e290fc00ea5dd14360baaf1e9a416378fc

test:
  secret_key_base: dc02629c7bbc76d5711bb06c16e53b29068315b55a077879d7e8e05b8e4f57a04dfba2105e8f85fbb88892ad82ce86da38ac374dcb3ac0e6ac4e1d3a9b36e0fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
